AWSTemplateFormatVersion: "2010-09-09"    
Resources:
  Parameters:
    InstanceTypeParameter:
        Type: String
        Default: t2.micro
        AllowedValues:
          - t1.micro
          - t2.nano
          - t2.micro
          - t2.small
          - t2.medium
          - t2.large
          - m1.small
          - m1.medium
          - m1.large
          - m1.xlarge
          - m2.xlarge
          - m2.2xlarge
          - m2.4xlarge
          - m3.medium
          - m3.large
          - m3.xlarge
          - m3.2xlarge
          - m4.large
          - m4.xlarge
          - m4.2xlarge
          - m4.4xlarge
          - m4.10xlarge
          - c1.medium
          - c1.xlarge
          - c3.large
          - c3.xlarge
          - c3.2xlarge
          - c3.4xlarge
          - c3.8xlarge
          - c4.large
          - c4.xlarge
          - c4.2xlarge
          - c4.4xlarge
          - c4.8xlarge
          - g2.2xlarge
          - g2.8xlarge
          - r3.large
          - r3.xlarge
          - r3.2xlarge
          - r3.4xlarge
          - r3.8xlarge
          - i2.xlarge
          - i2.2xlarge
          - i2.4xlarge
          - i2.8xlarge
          - d2.xlarge
          - d2.2xlarge
          - d2.4xlarge
          - d2.8xlarge
          - hi1.4xlarge
          - hs1.8xlarge
          - cr1.8xlarge
          - cc2.8xlarge
          - cg1.4xlarge
        Description: Enter instance size. Default is m3.medium.
    SubnetId:
        Type: String
        Default: subnet-ee74d194
    AMI:
        Type: String
        Default: ami-ac8dbdc9
    SecurityGroupId:
        Type: String
        Default: sg-a19f7acb
    SecurityKeyName:
        Type: String
        Default: OhioTestEnvironment
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      SubnetId: !Ref SubnetId
      InstanceType: 
        - Ref: InstanceTypeParameter
      SecurityGroupIds: !Ref SecurityGroupId
      KeyName: 
        - Ref: SecurityKeyName
      Tags:
        -
          Key: Name
          Value: Instance
      UserData:
        Fn::Base64: !Join
          - ''
          -
            - |-
              <powershell>
              Start-Transcript -path "C:\Bootstrap.txt" -append

              Write-Host "Configure IIS"
              Dism /Online /Enable-Feature /FeatureName:IIS-ASPNET /All
              Dism /Online /Enable-Feature /FeatureName:IIS-ASPNET45 /All
              Dism /Online /Enable-Feature /FeatureName:IIS-CertProvider /All
              Dism /Online /Enable-Feature /FeatureName:IIS-HttpRedirect /All
              Dism /Online /Enable-Feature /FeatureName:IIS-BasicAuthentication /All
              Dism /Online /Enable-Feature /FeatureName:IIS-WebSockets /All
              Dism /Online /Enable-Feature /FeatureName:IIS-ApplicationInit /All
              Dism /Online /Enable-Feature /FeatureName:IIS-CustomLogging /All
              Dism /Online /Enable-Feature /FeatureName:IIS-ManagementService /All
              Dism /Online /Enable-Feature /FeatureName:WCF-Services45 /All
              Dism /Online /Enable-Feature /FeatureName:WCF-HTTP-Activation45 /All
              Dism /Online /Enable-Feature /FeatureName:IIS-WindowsAuthentication /All
              Dism /online /enable-feature /featurename:NetFX3 /All

              Write-Output "Open port 8088 on Windows Firewall"
              & netsh.exe firewall add portopening TCP 8088 "Trading Website"

              $tentacleDownloadPath = "https://octopus.com/downloads/latest/WindowsX64/OctopusTentacle"
              $octopusServerUrl = "#{OctopusUrl}"
              $octopusApiKey = "#{OctopusApiKey}"
              $octopusServerThumbprint = "#{OctopusServerThumbprint}"
              $registerInEnvironments = "#{OctopusEnvironment}"
              $registerInRoles = "#{OctopusRole}"
              $tentacleListenPort = 10933
              $tentacleHomeDirectory = "C:\Octopus"
              $tentacleAppDirectory = "C:\Octopus\Applications"
              $tentacleConfigFile = "C:\Octopus\Tentacle\Tentacle.config"

              $tentaclePath = "C:\Tools\Octopus.Tentacle.msi"

              function Get-MyPublicIPAddress {
                  # Get Ip Address of Machine
                  Write-Host "Getting public IP address"
                  $ipAddress = Invoke-RestMethod http://ipinfo.io/json | Select-Object -exp ip
                  return $ipAddress
              }

              function Get-FileFromServer
              {
                param (
                  [string]$url,
                  [string]$saveAs
                )

                Write-Host "Downloading $url to $saveAs"
                [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
                $downloader = new-object System.Net.WebClient
                $downloader.DownloadFile($url, $saveAs)
              }

              function Install-Tentacle
              {
                param (
                   [Parameter(Mandatory=$True)]
                   [string]$apiKey,
                   [Parameter(Mandatory=$True)]
                   [System.Uri]$octopusServerUrl
                )

                Write-Output "Beginning Tentacle installation"

                Write-Output "Downloading latest Octopus Tentacle MSI..."

                $tentaclePath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(".\Tentacle.msi")
                if ((test-path $tentaclePath) -ne $true) {
                  Get-FileFromServer $tentacleDownloadPath $tentaclePath
                }

                Write-Output "Installing MSI"
                $msiExitCode = (Start-Process -FilePath "msiexec.exe" -ArgumentList "/i Tentacle.msi /quiet" -Wait -Passthru).ExitCode
                Write-Output "Tentacle MSI installer returned exit code $msiExitCode"
                if ($msiExitCode -ne 0) {
                  throw "Installation aborted"
                }

                Write-Output "Open port $tentacleListenPort on Windows Firewall"
                & netsh.exe firewall add portopening TCP $tentacleListenPort "Octopus Tentacle"
                if ($lastExitCode -ne 0) {
                  throw "Installation failed when modifying firewall rules"
                }

                $ipAddress = Get-MyPublicIPAddress
                $ipAddress = $ipAddress.Trim()

                Write-Output "Public IP address: " + $ipAddress

                Write-Output "Configuring and registering Tentacle"

                Set-Location "${env:ProgramFiles}\Octopus Deploy\Tentacle"

                & .\tentacle.exe create-instance --instance "Tentacle" --config $tentacleConfigFile --console | Write-Host
                if ($lastExitCode -ne 0) {
                  throw "Installation failed on create-instance"
                }
                & .\tentacle.exe configure --instance "Tentacle" --home $tentacleHomeDirectory --console | Write-Host
                if ($lastExitCode -ne 0) {
                  throw "Installation failed on configure"
                }
                & .\tentacle.exe configure --instance "Tentacle" --app $tentacleAppDirectory --console | Write-Host
                if ($lastExitCode -ne 0) {
                  throw "Installation failed on configure"
                }
                & .\tentacle.exe configure --instance "Tentacle" --port $tentacleListenPort --console | Write-Host
                if ($lastExitCode -ne 0) {
                  throw "Installation failed on configure"
                }
                & .\tentacle.exe new-certificate --instance "Tentacle" --console | Write-Host
                if ($lastExitCode -ne 0) {
                  throw "Installation failed on creating new certificate"
                }
                & .\tentacle.exe configure --instance "Tentacle" --trust $octopusServerThumbprint --console  | Write-Host
                if ($lastExitCode -ne 0) {
                  throw "Installation failed on configure"
                }
                & .\tentacle.exe register-with --instance "Tentacle" --server $octopusServerUrl --role "Database-TerraForm" --role "Web-TerraForm" --environment "Dev" --environment "Test" --environment "Pre-Prod" --environment "Production" --name $env:COMPUTERNAME --publicHostName $ipAddress --apiKey $apiKey --comms-style TentaclePassive --force --console | Write-Host
                if ($lastExitCode -ne 0) {
                  throw "Installation failed on register-with"
                }

                & .\tentacle.exe service --instance "Tentacle" --install --start --console | Write-Host
                if ($lastExitCode -ne 0) {
                  throw "Installation failed on service install"
                }

                Write-Output "Tentacle commands complete"
              }

              # Install tentacle now ...
              Install-Tentacle -apikey $octopusApiKey -octopusServerUrl $octopusServerUrl
              </powershell>