AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    Description: Enter instance size. Default is m3.medium.
  AMI:
    Type: String
    Default: ami-ac8dbdc9
    Description: AMI Image
  SubnetIdParameter:
    Type: String
    Default: subnet-ee74d194
  SecurityGroupIdParameter:
    Type: String
    MinLength: "1"
    Default: sg-a19f7acb
Resources:
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      SubnetId: !Ref SubnetIdParameter
      InstanceType: 
        Ref: InstanceTypeParameter
      SecurityGroupIds: 
        - 
          !Ref SecurityGroupIdParameter
      KeyName: OhioTestEnvironment
      Tags:
        -
          Key: Name
          Value: Instance
      UserData:
        Fn::Base64: !Join
          - ''
          -
            - |-
              <powershell>
              Start-Transcript -path "C:\Bootstrap.txt" -append

              Write-Host "Configure IIS"
              Dism /Online /Enable-Feature /FeatureName:IIS-ASPNET /All
              Dism /Online /Enable-Feature /FeatureName:IIS-ASPNET45 /All
              Dism /Online /Enable-Feature /FeatureName:IIS-CertProvider /All
              Dism /Online /Enable-Feature /FeatureName:IIS-HttpRedirect /All
              Dism /Online /Enable-Feature /FeatureName:IIS-BasicAuthentication /All
              Dism /Online /Enable-Feature /FeatureName:IIS-WebSockets /All
              Dism /Online /Enable-Feature /FeatureName:IIS-ApplicationInit /All
              Dism /Online /Enable-Feature /FeatureName:IIS-CustomLogging /All
              Dism /Online /Enable-Feature /FeatureName:IIS-ManagementService /All
              Dism /Online /Enable-Feature /FeatureName:WCF-Services45 /All
              Dism /Online /Enable-Feature /FeatureName:WCF-HTTP-Activation45 /All
              Dism /Online /Enable-Feature /FeatureName:IIS-WindowsAuthentication /All
              Dism /online /enable-feature /featurename:NetFX3 /All
              </powershell>