AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    Description: Enter instance size. Default is m3.medium.
  AMI:
    Type: String
    Default: ami-ac8dbdc9
    Description: AMI Image
  SubnetId:
    Type: String
    Default: subnet-ee74d194
  SecurityGroupId:
    Type: String
    Default: sg-a19f7acb
Resources:
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      SubnetId: !Ref SubnetId
      InstanceType: 
        Ref: InstanceTypeParameter
      SecurityGroupIds: !Ref SecurityGroupId
      KeyName: OhioTestEnvironment
      Tags:
        -
          Key: Name
          Value: Instance      